<?php

namespace app\modules\quanly\models\form;

use yii\base\Model;
use yii\db\Query;
use yii\data\ActiveDataProvider;
use app\modules\quanly\models\Diemthugom;

class FormThongkekhonggian extends Model
{
    public $geo_x;
    public $geo_y;
    public $bankinh;

    public function rules()
    {
        return [
            [['geo_x','geo_y','bankinh'],'required','message' => 'Thông tin bắt buộc!'],
            [['geo_x','geo_y'],'string'],
            [['bankinh'],'integer'],
        ];
    }

    public function attributeLabels()
    {
        return [
            'geo_x' => 'Vĩ độ',
            'geo_y' => 'Kinh độ',
            'bankinh' => 'Bán kính (m)',
        ]; // TODO: Change the autogenerated stub
    }

    // public function check()
    // {
    //     $sql_point = "st_transform(st_setsrid(st_makepoint($this->geo_x, $this->geo_y), 4326), 32648)";
    //     $sql_circle = "st_buffer($sql_point, $this->bankinh)";
    //     $sql_geom = "st_transform(st_setsrid(geom, 4326), 32648)";
    //     $sql_contains = "st_contains($sql_circle, $sql_geom)";
    //     $data = (new Query())->select(['diemdanh.id,hocsinh.hoten, diemdanh.lydonghi_id, diemdanh.date as ngay_nghi, diemdanh.chandoan_id, diemdanh.trieuchung, st_x(diemvenha.geom) as geo_x, st_y(diemvenha.geom) as geo_y, ST_Distance(st_transform(st_setsrid(st_makepoint(' . $this->geo_x . ',' . $this->geo_y . '), 4326), 32648),st_transform(st_setsrid(diemvenhageom, 4326),32648))  as dist'])
    //         ->from('diem_danh')
    //         ->leftJoin('hocsinh','diemdanh.hocsinh_id = hocsinh.id')
    //         ->leftJoin('diemvenha','hocsinh.diemvenha_id = diemvenha.id')
    //         ->andWhere($sql_contains)
    //         ->andFilterWhere(['diemdanh.status' => 1])
    //         ->all();

    //     return $data;
    // }

    public function searchKhonggian($params){
        $query = Diemthugom::find()
        ->where('geom is not null');

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);

        $this->load($params);

        if (!$this->validate()) {
            // uncomment the following line if you do not want to return any records when validation fails
            // $query->where('0=1');
            return $dataProvider;
        }

        if($this->geo_x != null && $this->geo_y != null && $this->bankinh != null){
            $sql_point = "st_transform(st_setsrid(st_makepoint($this->geo_x, $this->geo_y), 4326), 32648)";
            $sql_circle = "st_buffer($sql_point, $this->bankinh)";
            $sql_geom = "st_transform(st_setsrid(geom, 4326), 32648)";
            $sql_contains = "st_contains($sql_circle, $sql_geom)";
            $query->andWhere($sql_contains);
        }

        return $dataProvider;
    }

}